export const ErrorCode = {
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  LOGIN_FAILED: "LOGIN_FAILED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  LOCATION_ALREADY_EXISTS: "LOCATION_ALREADY_EXISTS",
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  ITEM_ALREADY_EXISTS: "ITEM_ALREADY_EXISTS",
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
