export const ErrorCode = {
  ITEM_ALREADY_EXISTS: "ITEM_ALREADY_EXISTS",
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;